version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: physipro-postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-physipro}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - physipro-network

networks:
  physipro-network:
    driver: bridge

volumes:
  postgres-data:
