services:
  app:
    build:
      context: ../..
      dockerfile: docker/prod/Dockerfile
    container_name: physipro-api
    restart: unless-stopped
    ports:
      - '${PORT:-3000}:3000'
    depends_on:
      - postgres
    environment:
      NODE_ENV: production
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME:-physipro}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-24h}
    networks:
      - physipro-network

  postgres:
    image: postgres:14-alpine
    container_name: physipro-postgres-prod
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-physipro}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - physipro-network

networks:
  physipro-network:
    driver: bridge

volumes:
  postgres-data:
